# generate client keys
---
- name: Copy openssl client extensions
  copy:
    src: openssl-client.ext
    dest: "{{openvpn_key_dir}}"
    owner: root
    group: root
    mode: 0400

- name: generate client key
  command: "openssl req -nodes -newkey rsa:{{openvpn_rsa_bits}} -keyout {{item.name}}.key -out {{item.name}}.csr -days 3650 -subj /CN=OpenVPN-Client-{{ inventory_hostname[:24] }}-{{ item.name[:24] }}/"
  args:
    chdir: "{{ openvpn_key_dir }}"
    creates: "{{item.name}}.key"
  with_items: "{{clients}}"

- name: protect client keys
  file:
    path: "{{openvpn_key_dir}}/{{item.name}}.key"
    mode: 0400
  with_items: "{{clients}}"

- name: sign client key
  command: openssl x509 -req -in {{item.name}}.csr -out {{item.name}}.crt -CA ca.crt -CAkey ca-key.pem -sha256 -days 3650 -extfile openssl-client.ext
  args:
    chdir: "{{openvpn_key_dir}}"
    creates: "{{item.name}}.crt"
  with_items: "{{clients}}"

- name: register server ca key
  slurp:
    src: "{{openvpn_key_dir}}/ca.crt"
  register: ca_cert

- name: register tls-auth key
  slurp:
    src: "{{openvpn_key_dir}}/ta.key"
  register: tls_auth

- name: register client certs
  slurp:
    src: "{{openvpn_key_dir}}/{{item.name}}.crt"
  with_items: "{{clients}}"
  register: client_certs

- name: register client keys
  slurp:
    src: "{{openvpn_key_dir}}/{{item.name}}.key"
  with_items: "{{clients}}"
  register: client_keys

- name: register client static ip
  template:
    src: client.j2
    dest: "{{openvpn_base_dir}}/client/OpenVPN-Client-{{ inventory_hostname[:24] }}-{{ item.name[:24] }}"
    owner: root
    group: root
    mode: 0744
  with_items: "{{clients}}"
  when: 
    - item.static is defined

- name: unregister client static ip
  file:
    path: "{{openvpn_base_dir}}/client/OpenVPN-Client-{{ inventory_hostname[:24] }}-{{ item.name[:24] }}"
    state: absent
  with_items: "{{clients}}"
  when: 
    - item.static is undefined

- name: test
  debug:
    msg: "{{ item }}"
  with_together:
    - "{{client_certs.results}}"
    - "{{client_keys.results}}"
    
    
- name: generate client config
  template:
    src: client.ovpn.j2
    dest: "{{ openvpn_base_dir }}/{{item.0.item.name}}-{{inventory_hostname}}.ovpn"
    owner: root
    group: root
    mode: 0400
  with_together:
    - "{{client_certs.results}}"
    - "{{client_keys.results}}"
    

- name: fetch client config
  fetch:
    src: "{{ openvpn_base_dir }}/{{item.name}}-{{inventory_hostname}}.ovpn"
    dest: "{{ openvpn_fetch_config_dir }}/{{item.name}}/{{inventory_hostname}}.ovpn"
    flat: yes
  with_items: "{{clients}}"
